# The URL the site will be built for
base_url = "https://lkt-icu.netlify.app/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "vonge"
taxonomies = [{ name = "tags", feed = true }]

# Title section.
title = "Lockey"
description = "Homepage of Lockey Team"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Unset logo image to display title in the upper left corner.
logo_image = ""

# Social links.
social_icons = [{ url = "https://github.com/lockey-org", icon = "GitHub" }]
social_media_share_image = "logo-light.webp"

# Hero section.
[[extra.content_blocks]]
block = "hero"
title = "Welcome to Lockey Homepage!"
description_html = """
<strong>Lockey</strong> was born from the meeting of <em>Ice Year</em> and <em>Yonzilch</em> during their student days. Along the journey of exploring technology, they met other like-minded members and formed this <strong>tech team</strong>. We are passionate about exploring Linux, cutting-edge technologies, and everything we love.
"""
image = "logo-light.webp"
image_alt = "Lockey Logo"
cta_button_link = "#projects"
cta_button = "Our Projects"
works_button_link = "#members"
works_button = "Team Members"

# Project section.
[[extra.content_blocks]]
block = "projects-section"
title = "Projects"
description_html = ""
show_projects = true
projects = [
  { name = "Matrix", link = "https://web.lkt.icu/", image = "https://raw.githubusercontent.com/matrix-org/matrix.org/refs/heads/main/static/images/matrix-logo.svg" },
  { name = "SearXNG", link = "https://search.lkt.icu/", image = "https://docs.searxng.org/_static/searxng-wordmark.svg" },
  { name = "Miniflux", link = "https://rss.lkt.icu/", image = "https://raw.githubusercontent.com/miniflux/logo/101354aa925848287e5ad1b6c40237dce7d852b8/icon.svg" },
  { name = "Lockey ID", link = "https://id.lkt.icu/", image = "https://raw.githubusercontent.com/sebadob/rauthy/559481ea86dfcac76420558bd2a5ff76863256b8/assets/logo/rauthy_dark.svg" },
  { name = "Ryot", link = "https://ryot.lkt.icu/", image = "https://raw.githubusercontent.com/IgnisDa/ryot/refs/heads/main/libs/assets/icon-512x512.png" },
  { name = "Jellyfin", link = "https://https://jellyfin.lkt.icu/", image = "https://raw.githubusercontent.com/jellyfin/jellyfin.org/ee39d9e1beb1241e72acaeed23407a42493ec770/static/images/icon-transparent.svg" },
  { name = "Lockey Mail", link = "https://mail.lkt.icu/", image = "https://roundcube.net/images/roundcube_logo_icon.svg" },
]

# Member section.
[[extra.content_blocks]]
block = "testimonials-section"
title = "Members"
description_html = ""
show_testimonials = true

# Footer section.
[extra.footer]
menu = []
copyright = "© 2023-2025 Lockey"
